version: '2'
services:
    sampleproject-app:
        image: sampleproject
        external_links:
            - sampleproject-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=sampleProject
        ports:
            - 8080:8080
    sampleproject-mongodb:
        extends:
            file: mongodb.yml
            service: sampleproject-mongodb
