version: '2'
services:
    sampleproject-mongodb:
        container_name: sampleproject-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/sampleProject/mongodb/:/data/db/
