version: '2'
services:
    sampleproject-mongodb:
        container_name: sampleproject-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        command: mongos --configdb sampleproject-mongodb-config
    sampleproject-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    sampleproject-mongodb-config:
        image: mongo:3.2.3
        container_name: sampleproject-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
